---

namespace: 'oxlorg'
name: 'linuxha'
version: 1.0.3
readme: 'README.md'
authors:
  - 'OXL IT Services <contact+linuxha@oxl.at>'
description: "Ansible Modules to manage LinuxHA/CoroSync"
license_file: 'LICENSE.txt'
tags:
  - 'highavailability'
  - 'availability'
  - 'ha'
  - 'cluster'
  - 'clustering'
  - 'linuxha'
  - 'linux'
  - 'corosync'
  - 'crmsh'
  - 'pacemaker'
  - 'failover'
dependencies: {}
repository: 'https://github.com/O-X-L/ansible-collection/linuxha'
documentation: 'https://ansible-linuxha.oxl.app'
homepage: 'https://www.OXL.at'
issues: 'https://github.com/O-X-L/ansible-collection//issues'
build_ignore: [
  '*_pytest.py', '*_testdata.py', '*pytest_cache', '*/_tmpl.py',
  '.**', 'pytest.ini', 'requirements_*.txt',
  'docs**', 'scripts**', 'venv**', 'Makefile', 'legacy**',
]
